# Site settings
title: courses.umn.edu
email: asrwebteam@umn.edu
description: > # this means to ignore newlines until "baseurl:"
  Documentation of the courses.umn.edu data service
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://umn-asr.github.io/courses/"
github_username:  umn-asr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
excerpt_separator: <!--break-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "vendor", "Gemfile", "Gemfile.lock"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
