#!/bin/sh

# script/deploy: Deploy the application
#   change the url opened at the end of the script to the URL of the application, if applicable


set -e

cd "$(dirname "$0")/.."

echo "===> Running bundle-audit"
bundle exec bundle-audit check --update

echo "===> Deploying to $1"
bundle exec cap "$1" deploy
