#!/bin/bash

# script/deploy: Tells Docker to run its deploy script

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
  docker compose exec web script/_deploy "$1"
else
  docker compose exec web script/_deploy
fi
