#!/bin/bash

# script/server: Tells Docker to run docker compose to start containers up and
# display running logs.

set -euo pipefail

cd "$(dirname "$0")/.."

docker compose up -d
docker compose logs -f web
